### ISSUE TITLE
bad link to access to the french resume

### ISSUE THREAD

**Issue by davidaparicio** [nical/kiwi#11]
Hi Nical,

You have a bad link on README.md :
http://github.com/nical/resume/raw/master/fr/NicolasSilva.pdf instead of : http://github.com/nical/resume/raw/master/fr/svg/pdf/NicolasSilva.pdf :)

**Comment by nical** [comment]
Thanks, it's fixed (removed the french resume :p). Actually all the resumes were out of date, I kinda forgot about this repo...
