### ISSUE TITLE
Problème de compilation

### ISSUE THREAD

**Issue by MaximeGaudin** [nical/kiwi#3]
Lorsque je compile (MacOSX Snow Leopard), CMake me sort :

CMake Error at CMakeLists.txt:54 (find_package):
  Could not find module FindCairo.cmake or a configuration file for package
  Cairo.

  Adjust CMAKE_MODULE_PATH to find FindCairo.cmake or set Cairo_DIR to the
  directory containing a CMake configuration file for Cairo.  The file will
  have one of the following names:

```
CairoConfig.cmake
cairo-config.cmake
```

J'ai pourtant cairo d'installé. Une idée ?

**Comment by tvuillemin** [comment]
Salut,

Comme il n'y a pas encore de véritable script d'installation, tu dois copier à la main le fichier kiwi/utils/FindCairo.cmake dans le dossier de modules de CMake. Sous Ubuntu, depuis le dossier kiwi, ça donne :

```
$ sudo cp utils/FindCairo.cmake /usr/share/cmake-2.8/Modules/.
```

N'hésite pas à nous donner la commande exacte sous Mac, ça nous intéresse. Par ailleurs, cette info est disponible sur la page https://github.com/nical/kiwi/wiki/Getting-started . Le wiki est pas encore exemplaire pour l'instant, mais on devrait trouver le temps de l'améliorer pendant les vacances de Noël.

Bonne compil !

**Comment by nical** [comment]
Pour effectuer correctement les inclusions et l'édition des liens vers les bibliothèques externes, CMake utilise des scripts FindXXX.cmake (avec XXX le nom de la bibliothèque en question). Un script FindCairo.cmake est disponible dans le dossier utils du dépot git (script écrit par Pino Toscano sous license NewBSD). Sous linux le script doit être placé dans le dossier de modules de cmake:
$ sudo cp  utils/FindCairo.cmake  /usr/share/cmake-*/Modules/

Je ne sais pas exactement où doit être placé le fichier sur windows ou mac mais ça m'intéresse de savoir si Kiwi et passe les tests sur ces deux systèmes.

Au passage: 
- le script FindBoost.cmake est habituellement fourni avec cmake mais en cas de problème avec boost, on ne sait jamais ça peut venir de là...
- depuis peu kiwi utilise boost::filesystem, qui ne fait pas partie du package (du moins sous debian et ubuntu) libboost-dev. Il y aura peut être besoin pour certains d'installer libboost-all ou au moins le paquet concernant filesystem.

**Comment by MaximeGaudin** [comment]
Salut !

Pour ceux qui utilisent MacPort, ça donne, à partir de kiwi/. un truc du genre :

sudo port install boost cairo cmake
sudo cp utils/FindCairo.cmake /opt/local/share/cmake-2.8/Modules
cmake .

À bientôt !
