### ISSUE TITLE
library not found for -lboost_filesystem 

### ISSUE THREAD

**Issue by MaximeGaudin** [nical/kiwi#4]
Je confirme que le port de boost par défaut sur Mac ne contient pas la partie filesystem.
SI je trouve un solution, je vous tiens au courant.

++

**Comment by nical** [comment]
J'ai changé les CMakeLists de sorte qu'on peut maintenant désactiver la construction de certaines parties de kiwi en commentant une ou plusieurs des lignes suivantes:
- set(BUILD_KIWI_TESTS "yes")
- set(BUILD_KIWI_IMAGE "yes")
- set(BUILD_KIWI_TEXT "yes")
- set(BUILD_KIWI_CMDLINE "yes")

dans le CMakeLists.txt à la racine du projet.
Pour ceux qui n'ont pas boost::filesystem il faut commenter la ligne :
- set(BUILD_KIWI_CMDLINE "yes")
