### ISSUE TITLE
[MAC] - Problème de compilation 

### ISSUE THREAD

**Issue by MaximeGaudin** [nical/kiwi#8]
Encore un petit souci de compilation sur MAC :

```
Scanning dependencies of target UnorderedArrayTest
[ 91%] Building CXX object test/CMakeFiles/utils/UnorderedArrayTest.dir/utils/UnorderedArrayTest.o
/tmp/kiwi/test/utils/ConnectorTest.cpp: In function ‘int main()’:
/tmp/kiwi/test/utils/ConnectorTest.cpp:83: error: cast from ‘C*’ to ‘int’ loses precision
/tmp/kiwi/test/utils/ConnectorTest.cpp:83: error: cast from ‘C*’ to ‘int’ loses precision
```

**Comment by padenot** [comment]
Ça, c'est un probleme d'archi, non ? 
C\* : 32 bits : 4octets, 64 bits : 8octets
int : 4 octets dans les deux cas.

**Comment by nical** [comment]
Ok j'ai retiré la ligne en question, elle m'avait juste aidé à constater le décalage de pointeur en downcastant une classe dans certains cas (ex: héritage multiple).

int n'est pas sensé être de la même taille qu'un pointeur sur toutes les archi ? en tout cas un int est bien sur 64 bits sur mon laptop (ubuntu 64).

Au passage je suis étonné que ça ait provoqué une erreur et non un warning.

**Comment by MaximeGaudin** [comment]
Ça c'est parce que les paramètres de mon compilo ne laissent rien passer (comme on l'avait constaté la dernière fois)
